import stones from './assets/massagem_relaxantecomPedras.jpeg'
import electro from './assets/Massagem_EletroEstimulacao02.png'

export interface Duration { minutes: number; single: number; twice: number; four: number }
export interface Service { id: string; name: string; shortName: string; subtitle: string; description: string; image: string; imageAlt: string; benefits: string[]; techniques: { name: string; description: string }[]; durations: Duration[] }
export const services: Service[] = [
  { id: 'manual', name: 'Massagem manual', shortName: 'Manual, pedras quentes e ventosas', subtitle: 'Com pedras quentes e ventosas', description: 'O toque que acolhe, o calor que relaxa. Um cuidado para desacelerar e aliviar as tensões acumuladas no dia a dia.', image: stones, imageAlt: 'Sessão de massagem com pedras quentes posicionadas nas costas', benefits: ['Relaxamento e alívio das tensões', 'Cuidado com a rigidez e os nódulos musculares', 'Sensação de leveza e bem-estar'], techniques: [{ name: 'Toque manual', description: 'Movimentos direcionados aos pontos de tensão e à musculatura.' }, { name: 'Pedras quentes', description: 'O calor das pedras complementa a experiência de relaxamento muscular.' }, { name: 'Ventosas', description: 'Técnica complementar aplicada conforme a avaliação e a necessidade de cada pessoa.' }], durations: [{ minutes: 60, single: 200, twice: 350, four: 600 }, { minutes: 30, single: 98, twice: 160, four: 300 }] },
  { id: 'integrada', name: 'Massagem integrada', shortName: 'Relaxante, miofascial e terapêutica', subtitle: 'Relaxante · Miofascial · Terapêutica', description: 'Massagem manual e recursos complementares para um cuidado individualizado com as tensões, a sobrecarga e o cansaço físico.', image: electro, imageAlt: 'Aplicação de eletrodos na região das costas durante atendimento', benefits: ['Cuidado com tensões profundas e desconfortos', 'Atenção à mobilidade e ao relaxamento', 'Uma pausa para o corpo e a mente'], techniques: [{ name: 'Massagem manual', description: 'Abordagem relaxante, miofascial ou terapêutica, conforme a avaliação.' }, { name: 'ILIB e corrente subsensorial', description: 'Recursos complementares cuja indicação e aplicação são avaliadas pela profissional. Tire suas dúvidas antes da sessão.' }, { name: 'Ventosas ou pedras quentes', description: 'Complementam o atendimento conforme suas necessidades e a orientação da especialista.' }], durations: [{ minutes: 60, single: 250, twice: 450, four: 800 }, { minutes: 40, single: 170, twice: 300, four: 540 }] },
]
export const money = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 2, minimumFractionDigits: Number.isInteger(value) ? 0 : 2 }).format(value)
export const whatsapp = (message = 'Olá, Deyse! Vim pela página de massagens e gostaria de conversar sobre um atendimento.') => `https://wa.me/5521977353902?text=${encodeURIComponent(message)}`
export function booking(service: Service, duration: Duration, sessions = 1) {
  const total = sessions === 4 ? duration.four : sessions === 2 ? duration.twice : duration.single
  return whatsapp(`Olá, Deyse! Quero saber mais sobre ${service.shortName}, com ${duration.minutes} minutos. Tenho interesse ${sessions === 1 ? 'na sessão avulsa' : `no plano de ${sessions} sessões ao mês`}, por ${money(total)}${sessions === 1 ? '' : ' no total mensal'}. Podemos conversar sobre a indicação e os horários disponíveis?`)
}
